//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprendiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aprendiz()
        {
            this.Ingreso = new HashSet<Ingreso>();
            this.Rutina = new HashSet<Rutina>();
        }
    
        public int idAprendiz { get; set; }
        public string nombreAprendiz { get; set; }
        public string correoAprendiz { get; set; }
        public string claveAprendiz { get; set; }
        public int fichaAprendiz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rutina> Rutina { get; set; }
    }
}
