//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesRutina
    {
        public int idDetalle { get; set; }
        public int idEjercicio { get; set; }
        public int numRepeticiones { get; set; }
        public int numSeries { get; set; }
        public int idRutina { get; set; }
    
        public virtual Ejercicios Ejercicios { get; set; }
        public virtual Rutina Rutina { get; set; }
    }
}
