//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicios()
        {
            this.DetallesRutina = new HashSet<DetallesRutina>();
        }
    
        public int idEjercicio { get; set; }
        public string nombreEjercicio { get; set; }
        public string nombreGrupoMuscular { get; set; }
        public Nullable<int> idMaquina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesRutina> DetallesRutina { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual GrupoMuscular GrupoMuscular { get; set; }
    }
}
