//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int idIngreso { get; set; }
        public int idAprendiz { get; set; }
        public string horaIngreso { get; set; }
        public string horaSalida { get; set; }
    
        public virtual Aprendiz Aprendiz { get; set; }
    }
}
