//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int idReporte { get; set; }
        public string tipoReporte { get; set; }
        public Nullable<int> numMaDisponible { get; set; }
        public Nullable<int> numMaNoDisponible { get; set; }
        public string fechaReporte { get; set; }
        public Nullable<int> noIngresos { get; set; }
        public Nullable<int> noAprendices { get; set; }
        public Nullable<int> idAdministrador { get; set; }
    
        public virtual Administrador Administrador { get; set; }
    }
}
